#!/usr/bin/env python3

# Complete the whatFlavors function below.
def whatFlavors(cost, money):
    #print(cost)
    lookup = {}
    for i,cost in enumerate(cost, 1):
        if money - cost in lookup:
            print(lookup[money-cost], i)
            return
        lookup[cost] = i

whatFlavors([1,4,5,3,2], 4)
