#!/usr/bin/env python3

def calcTrainingTime(skill, n, p, caseId):
    minTimeNeeded = -1
    skill.sort()
    if n == p:
        sum = 0
        for i in skill:
            sum += i
        minTimeNeeded = skill[n-1]*p - sum
    else:
        runningTimeNeeded = 0
        sum = 0
        for i in range(n):
            if i < p - 1:
                sum += skill[i]
            else:
                sum += skill[i]
                runningTimeNeeded = skill[i]*p - sum
                if ((minTimeNeeded > runningTimeNeeded) or (minTimeNeeded == -1)):
                    minTimeNeeded = runningTimeNeeded
                sum = sum - skill[i - p + 1]
    print("Case #{0}: {1}".format(caseId, minTimeNeeded))
                

if __name__ == '__main__':
    t = int(input())
    for i in range(t):
        np = input().split()
        n = int(np[0])
        p = int(np[1])
        skill = list(map(int, input().rstrip().split()))
        calcTrainingTime(skill, n, p, i+1)
