#!/usr/bin/env python3

if __name__ == '__main__':
    print("Enter number of tests:")
    t = int(input())
    for _ in range(t):
        print("Enter a range for number to be guessed:")
        ab = input().split()
        a = int(ab[0])
        b = int(ab[1])
        print("Enter number of guesses:")
        n = int(input())
        for i in range(n):
            guess = (a + b)//2
            print("Is your number {0} ?. Tell me if its TOO_BIG, TOO_SMALL or CORRECT".format(guess))
            decision = input().rstrip()
            if decision == 'TOO_BIG':
                b = guess - 1
            elif decision == 'TOO_SMALL':
                a = guess + 1
            elif decision == 'CORRECT':
                print("Yay! :)")
                break
            if i == n-1:
                print("Ran out of number of Guesses. :(")
                break
