#!/usr/bin/env python3

def sockMerchant(n, ar):
    pairs         = dict()
    numberOfPairs = 0
    
    for sock in ar:
        if sock in pairs:
            pairs[sock] += 1
            if pairs[sock] == 2:
                numberOfPairs += 1
                pairs[sock] = 0
        else:
            pairs[sock] = 1
    return numberOfPairs

print(sockMerchant(9, [10, 20, 20, 10, 10, 30, 50, 10, 20]))
print(sockMerchant(10,[1, 1, 3, 1, 2, 1, 3, 3, 3, 3])) 
